In [5]:
def isnum(n):
    n= str(n)
    if n.isdigit():
        return True
    return False
li = ["10","20","38","a"]
a = map(isnum,li)
list(a)


[True, True, True, False]

In [8]:
a=filter(isnum,li)
list(a)

['10', '20', '38']

# ***Lambda***


In [9]:
def sum1(a,b):
    c=a+b
    return c
sum1(8,9)

17

In [10]:
a = lambda x,y : x+y
a(7,8)

15

In [11]:
def squareof(a):
    b=a*a
    return b
squareof(9)

81

In [12]:
s = lambda x : x**2
s(3)

9

# ***List comprehension***

In [16]:
a = int(input("enter number:")) 
for i in range(0,a+1):
    print(i**2)

enter number:4
0
1
4
9
16


In [18]:
a = [i**2 for i in range(1,11)]
a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [26]:
def factorialof(n):
    fact=1
    for i in range(1,n+1):
        fact=fact*i
    print("the factorialof",n,"is",fact)

        
        

In [27]:
factorialof(6)

the factorialof 6 is 720


a = int(input("enter number:"))
b=1
for i in range(1,a+1):
    b*=i
print(b)


              

In [34]:
import math
s = [math.factorial(i)for i in range(1,11)]
s

[1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800]

# ***File handling***

* Performing operations on a file is called file handling.
* Entering some data to a file is called as write to a file.
* Retrieving data from a file is called as reading from a file.
* We can perform append,delete operations on files.

In [6]:
def writetoafile(filename,data):
    with open(filename,"w") as f:
        f.write(data)
    return
filename = "data.txt"
writetoafile(filename,"anantha\nbharadpandhi\n")
    
    

In [9]:
def readfromafile(filename):
    with open(filename,"r") as f:
        fd = f.read()
    return fd
readfromafile("data.txt")

'anantha\nbharadpandhi\n'

In [13]:
def readfromafile(filename):
    with open(filename,"r") as f:
        fd = f.read()
    return fd
readfromafile("data.txt")
def printlines(filename):
    with open(filename,"r") as f:
        for line in f:
            print(line,end = "")
    return
printlines(filename)
#print(readfromafile(filename))

anantha
bharadpandhi


In [14]:
def readfromafile(filename):
    with open(filename,"r") as f:
        fd = f.read()
    return fd
readfromafile("data.txt")
def printlines(filename):
    with open(filename,"r") as f:
        for line in f:
            print(line,end = "")
    return
#printlines(filename)
print(readfromafile(filename))

anantha
bharadpandhi



In [21]:
def readfromafile(filename):
    with open(filename,"r") as f:
        fd = f.read()
    return fd
filename = "anuu.txt"
readfromafile("anuu.txt")
def printlines(filename):
    with open(filename,"r") as f:
        for line in f:
            print(line,end = "")
    return
#printlines(filename)
print(readfromafile(filename))

def sumofnum(a,b):
    a=int(input("enter a:")
          b=int(input("enter b:")
                c = a+b
               
return c
sumofnum(1,2)


In [25]:
def appendtoffile(filename,data):
    with open(filename,"a") as f:
        for line in data:
            f.write("\n"+line)
        return
data = ["line3","line4","line5","line6"]
filename = "data.txt"
appendtoffile(filename,data)

# ***Numpy***

* ***Numpy is an advanced library*** 
* ***Numpy---Numerical pyhton***
* ***Numpy is to perform mathematical & statisctical operations***
* ***The values are represented in the form of rows & columns***


#### ***Advantages of Numpy when compared to lists***

* ***It takes less time***
* ***performance will be high*** 
* ***Occupies less memory***


In [5]:
import numpy as np

In [11]:
### creating an array in numpy
a = np.array([1,2,3,4])
a.size

4

In [9]:
### creating an array in particular range
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
### checking the number of elements
a.size

9

In [11]:
a+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
a2 = np.array([[1,2,3,4],[4,5,6,7]])
a2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [15]:
a2.size

8

In [8]:
a2 = np.array([[1,2,3,4],[4,5,6,7]],dtype = complex)
a2

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j]])

In [12]:
a.dtype

dtype('int32')

In [6]:
### comparison of two arrays
a = np.array([[1,2,3,4],[4,5,6,7]])
b = np.array([[5,6,7,8],[7,8,9,3]])



In [7]:
a >b

array([[False, False, False, False],
       [False, False, False,  True]])

In [9]:
a<b

array([[ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [10]:
a == b

array([[False, False, False, False],
       [False, False, False, False]])

In [14]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [16]:
np.ones([5,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.zeros([3,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
import numpy as np


In [6]:
a = np.array([[1,2,3,4],[4,5,6,7]],dtype = int)
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [7]:
a[0]

array([1, 2, 3, 4])

In [8]:
a[0:1,1:2]

array([[2]])

In [10]:
a[1:2,2:3]

array([[6]])

In [11]:
a[:,1:3]

array([[2, 3],
       [5, 6]])

In [12]:
a[:,0:2]

array([[1, 2],
       [4, 5]])

In [13]:
a.shape

(2, 4)

In [14]:
a.ndim

2

In [15]:
a.itemsize

4

In [16]:
a[:,1:2]

array([[2],
       [5]])

In [18]:
b=np.arange(3,9)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [19]:
max(b)

8

In [20]:
np.mean(b)

5.5

In [21]:
np.std(b)

1.707825127659933

In [22]:
np.sum(b)

33

In [23]:
np.var(b)

2.9166666666666665

In [24]:
np.cumsum(b)

array([ 3,  7, 12, 18, 25, 33], dtype=int32)

In [25]:
np.argmin(b)

0

In [26]:
np.argmax(b)

5

In [27]:
np.transpose(b)

array([3, 4, 5, 6, 7, 8])

## binary to decimal

In [28]:
def decimaltobinary(n):
    if n>1:
        decimaltobinary(n//2)
    print(n%2,end='')
n=(int(input("enter number:")))
decimaltobinary(n)

enter number:1010
1111110010